{{- if .Values.resources.frontend.enabled -}}
{{- if .Values.resources.frontend.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
spec:
  ingressClassName: {{ .Values.resources.frontend.ingress.className }}
  rules:
    - host: {{ .Values.resources.frontend.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 3000
          - path: /v1/
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend
                port:
                  number: 8080
  tls:
    - hosts:
        - {{ .Values.resources.frontend.ingress.hostname }}
      secretName: {{ .Values.resources.frontend.ingress.tlsSecret }}
{{- end }}
{{- end }}
