{{- if .Values.resources.mysql.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.image.mysql }}
          imagePullPolicy: {{ .Values.resources.mysql.imagePullPolicy }}
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_USER
              value: {{ .Values.env.db.user }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.env.db.password }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.env.db.password }}
            - name: MYSQL_DATABASE
              value: {{ .Values.env.db.name }}
{{- end }}