{{- if .Values.resources.webhook.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: webhook
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: webhook
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: webhook
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
